#!/bin/bash
urle () { [[ "${1}" ]] || return 1; local LANG=C i x; for (( i = 0; i < ${#1}; i++ )); do x="${1:i:1}"; [[ "${x}" == [a-zA-Z0-9.~-] ]] && echo -n "${x}" || printf '%%%02X' "'${x}"; done; echo; }

# Fetch FLAME data
echo -e "\nBefore you continue, you must register at https://tempeh.is.tue.mpg.de/ and agree to the license terms."
read -p "Username (FaMoS):" username
read -p "Password (FaMoS):" password
username=$(urle $username)
password=$(urle $password)

cd ~/datasets/FaMoS/
echo -e "\nDownloading images..."

for i in  {4..4}
do
    wget --post-data "username=$username&password=$password" "https://download.is.tue.mpg.de/download.php?domain=tempeh&resume=1&sfile=training_data/images/training_images_4.zip.00$i" -O "training_images_4.zip.00$i" --no-check-certificate --continue
    7z x "training_images_4.zip.00$i"
    rm -rf "training_images_4.zip.00$i"
done

# for i in  {10..19}
# do
#     wget --post-data "username=$username&password=$password" "https://download.is.tue.mpg.de/download.php?domain=tempeh&resume=1&sfile=test_data/training_images_4.zip.0$i" -O "training_images_4.zip.0$i" --no-check-certificate --continue
#     7z x "training_images_4.zip.0$i"
#     rm -rf "training_images_4.zip.0$i"
# done

# for i in  {1..2}
# do
#     wget --post-data "username=$username&password=$password" "https://download.is.tue.mpg.de/download.php?domain=tempeh&resume=1&sfile=test_data/test_images_4.zip.00$i" -O "test_images_4.zip.00$i" --no-check-certificate --continue
#     7z x "test_images_4.zip.00$i"
#     rm -rf "test_images_4.zip.00$i"
# done

cd ~/repos/face_animation
python3 clean_famos_image_dataset.py