save_dir: "./checkpoints" 
num_epoch: 500
dataset: "vocaset" 
dataset_path: "./dataset"
weight_decay: 0.001
batch_size: 16
gradient_accumulation_steps: 4
lr: 0.00001
cosine_scheduler: True
warmup_steps: 10
device: 0
num_workers: 8
diffusion_steps: 1000 
overwrite: True 
no_normalization: False
train_dataset_repeat_times: 20
input_motion_length: 60

cond_mask_prob: 0
fps: 30
# resume_checkpoint: 

# flame_params
n_exp: 50 
n_pose: 6 # jaw pose in 6d


# log
wandb_log: True
save_interval: 1 
log_interval: 1 

#model architecture
arch: "diffusion_AudioTrans_512d_2l_audio" 
latent_dim: 256
dropout: 0.2

use_mask: True  # use alibi mask

# unusable for gru
ff_size: 1024
num_enc_layers: 1
num_heads: 4

# unusable for transformer encoder 
num_dec_layers: 2