save_dir: "./checkpoints/calib/" 
num_epoch: 50
dataset: "FaMoS" 
dataset_path: "./processed_data"
weight_decay: 0.001
batch_size: 128
lr: 0.0005
save_interval: 5 
device: 0 
num_workers: 8 

# training setting
seed: 0
scale: 1.5 # scale min, scale max
trans_scale: 0.
image_size: 224

# model architechture
model_name: "trans_orth_reversey"
input_feature_dim: 136 # input feature dim 68 x 2
output_feature_dim: 3 # number of cam params (one set per frame)
latent_dim: 128