save_dir: "./checkpoints" 
num_epoch: 100
dataset: "multiface" 
dataset_path: "./dataset"
weight_decay: 0.0005
batch_size: 1
gradient_accumulation_steps: 128
lr: 0.0002
device: 0 
num_workers: 8 
train_dataset_repeat_times: 30
input_motion_length: 30
diffusion_steps: 1000 
lr_anneal_steps: 20000
overwrite: True 
no_normalization: False
occlusion_mask_prb: 0.2
fps: 30
# resume_checkpoint: "checkpoints/DiffMLP_PE_176lmk_2b_45l_64dP_256dE_50res/model_150.pt"

# diffusion
cond_mask_prob: 0

# log
wandb_log: True
save_interval: 1
log_interval: 1

#architecture
lmk2d_dim: 136  # 68x2
cond_latent_dim: 256
pose_latent_dim: 128
pose_num_layers:  1
exp_latent_dim: 256
exp_num_layers: 4
dropout: 0.0

arch: "diffusion_DiffMLP_4l_256d" 

# diffusion target size
n_exp: 50
n_pose: 6