save_dir: "./checkpoints" 
num_epoch: 200
dataset: "mead_25fps" 
dataset_path: "./dataset"
weight_decay: 0.0005
batch_size: 32
gradient_accumulation_steps: 4
lr: 0.0003
device: 0 
num_workers: 1 
train_dataset_repeat_times: 20
input_motion_length: 64
diffusion_steps: 1000 
lr_anneal_steps: 20000
overwrite: True 
no_normalization: False

fps: 25
freeze_audio_encoder_interval: 5
# resume_checkpoint: "checkpoints/DiffMLP_PE_176lmk_2b_45l_64dP_256dE_50res/model_150.pt"

# diffusion
cond_mask_prob: 0
audio_mask_prob: 0.2


# flame_params
n_shape: 300
n_exp: 50 
n_pose: 6 # jaw pose in 6d
load_tex: False
use_iris: False

# log
wandb_log: True
save_interval: 5
log_interval: 1

#architecture
lmk2d_dim: 936  # 68x2
cond_latent_dim: 256
input_latent_dim: 128
num_layers:  4
dropout: 0.0

arch: "diffusion_DiffMLP_4l_128d" 

# diffusion target size
n_exp: 50
n_pose: 6