save_dir: "./checkpoints/calib/fitcam" 
num_epoch: 20
dataset: "FaMoS" 
dataset_path: "./processed_data"
weight_decay: 0.001
batch_size: 128
lr: 0.0001
save_interval: 1 
device: 0 
num_workers: 8 

# training setting
seed: 0

# model architechture
model_name: "calib_32d"
lmk2d_dim: 136 # input feature dim 68 x 2
n_target: 180
output_feature_dim: 3 # number of cam params (one set per frame)
latent_dim: 32
ckpt_path: NULL

# for flame
flame_model_path: "flame_2020/generic_model.pkl"
flame_lmk_embedding_path: "flame_2020/dense_lmk_embedding.npy"