save_dir: "./checkpoints" 
num_epoch: 50
dataset: "mead_25fps" 
dataset_path: "./dataset"
weight_decay: 0.001
batch_size: 16
gradient_accumulation_steps: 4
lr: 0.0001
cosine_scheduler: False
warmup_steps: 100
device: 0 # -1 if using cpu for test
num_workers: 4
diffusion_steps: 1000 
overwrite: True 
train_dataset_repeat_times: 5
input_motion_length: 64

audio_mask_prob: 0.1
fps: 25
freeze_audio_encoder_interval: 6
# resume_checkpoint:

# flame_params
n_shape: 300
n_exp: 100 
n_pose: 3 # jaw pose in 6d
load_tex: False
use_iris: False


# log
wandb_log: True
save_interval: 1
log_interval: 1 

#model architecture
arch: "diffusion_Transformer_768d_FLINT" 
latent_dim: 768
dropout: 0.1

use_mask: False # use alibi mask

# unusable for gru
ff_size: 1536
num_enc_layers: 3
num_heads: 4

# unusable for transformer encoder 
num_dec_layers: 6
